### PR TITLE
feat: reworks k8s manifests generation to rely on kubebuilder

### LINKED ISSUE #536: k8s/controller runtime update
##### Issue Overview

Newest `controller-runtime` requires a newer version of k8s libarires (`release-1.19.0`), but this leads to build failures when using dep.

##### Expected Behaviour

Dependencies update can resolve all transitive dependencies

##### Current Behaviour

```
...
	k8s.io/apimachinery@kubernetes-1.19.0
	k8s.io/apimachinery@kubernetes-1.19.0
	k8s.io/apimachinery@kubernetes-1.19.0
	k8s.io/apimachinery@kubernetes-1.19.0
	release-4.0: Could not introduce sigs.k8s.io/structured-merge-diff@release-4.0, as its subpackage sigs.k8s.io/structured-merge-diff/v4/value is missing. Package is required by:
....
```

##### Steps To Reproduce

1. bump controller-runtime
2. bump k8s libs 
3. `make`

Probably blocked by #16 
Related PR: #533

### LINKED ISSUE #537: Operator SDK 1.0.0 update
##### Issue Overview

In order to provide new functionalities and autogeneration of manifests, we should upgrade Operator SDK (and kubebuilder when it's enough) to 1.x.

Depends on #536

### PR DESCRIPTION
**Pull request by bartoszmajsak**
Fixes #537
Fixes #536 

See related guides:

- https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide
- https://v1-0-x.sdk.operatorframework.io/docs/upgrading-sdk-version/v1.0.0/

### CODE REVIEW

**Comment by alien-ike** [comment]
@bartoszmajsak: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
e2e-tests-openshift | ebfc6f599949783db2ff5e1ee1da8f094ca3be1f | [link](http://status-prow.apps.workspace.maistra.test/view/gs/ike-prow-logs/pr-logs/pull/maistra_istio-workspace/538/e2e-tests-openshift/1350118331788562432) | `/test openshift`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by alien-ike** [comment]
@bartoszmajsak: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
e2e-tests-openshift | ebfc6f599949783db2ff5e1ee1da8f094ca3be1f | [link](http://status-prow.apps.workspace.maistra.test/view/gs/ike-prow-logs/pr-logs/pull/maistra_istio-workspace/538/e2e-tests-openshift/1351098790823596032) | `/test openshift`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by alien-ike** [comment]
@bartoszmajsak: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
e2e-tests-openshift | ebfc6f599949783db2ff5e1ee1da8f094ca3be1f | [link](http://status-prow.apps.workspace.maistra.test/view/gs/ike-prow-logs/pr-logs/pull/maistra_istio-workspace/538/e2e-tests-openshift/1351117539534442496) | `/test openshift`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Review by aslakknutsen — APPROVED** [review]

**Pull request merged**
