### PR TITLE
fix(template): creates replica if not exists

### LINKED ISSUE #341: Template patching should check if path exists
##### Issue Overview

If `/spec/template/spec/replicas` does not exist in modified resource it fails with error (which is expected).

##### Expected Behaviour

We should first check the existence of the path and only then apply the patch.

##### Current Behaviour

Works ok, as jsonpatch library in version `v3.4.0` silently omits (?) the error. Upgrading to the newest version (transitively through open-ended versioning) yields `msg: "replace operation does not apply: doc is missing key: /spec/template/spec/replicas"`.

### PR DESCRIPTION
**Pull request by bartoszmajsak**
#### Changes proposed in this pull request:

- check if `/spec/template/spec/replicas` exists. Creates if not before patching to `1`
- relaxes test assertion for wrong paths, as error msg changed between the versions of json-patch library

Fixes #341

### CODE REVIEW

**Comment by aslakknutsen** [comment]
Could have a test... but .. When does this issue come up?

**Comment by bartoszmajsak** [comment]
> Could have a test... but .. When does this issue come up?

Coming from a transitive update of, presumably, jsonpatch and then it's failing for missing `replica` path. So it is indirectly covered for the negative case. We don't have a deployment in test having that path at all - we assume it's there.

**Comment by aslakknutsen** [comment]
I meant where do we see it fail. Why would replicas be missing?

**Comment by bartoszmajsak** [comment]
> I meant where do we see it fail. Why would replicas be missing?

In unit tests - e.g. `k8s/deployment_test.go`

**Comment by aslakknutsen** [comment]
ah ic what you mean.

**Pull request merged**
