### PR TITLE
feat: introduces new job for building and pushing images

### PR DESCRIPTION
**Pull request by bartoszmajsak**
#### Short description of what this resolves:

CircleCI job to build images used by e2e tests

#### Changes proposed in this pull request:

- builds images as separated job
- bumps golang to 1.15.5
- sets host network access for docker builds

Part of #563

### CODE REVIEW

**Review by aslakknutsen — APPROVED** [review]

**Review by aslakknutsen — APPROVED** [review]

**Review by aslakknutsen — APPROVED** [review]

**Comment by alien-ike** [comment]
@bartoszmajsak: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
test-e2e | d57b22b713f8e7407d12a448875fdb493cb66f5a | [link]() | `/test test-e2e`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by alien-ike** [comment]
@bartoszmajsak: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
test-e2e | d57b22b713f8e7407d12a448875fdb493cb66f5a | [link]() | `/test test-e2e`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
