### PR TITLE
fix(tekton): reworks shell scripts to comply with SC

### PR DESCRIPTION
**Pull request by bartoszmajsak**
#### Short description of what this resolves:

PR to Tekton Catalog [1] revealed few weak spots in our sh scripts wrapped in Tekton YAML. This PR addresses those findings

#### Changes proposed in this pull request:

- https://github.com/koalaman/shellcheck/wiki/SC2155
- https://github.com/koalaman/shellcheck/wiki/SC2181

[1] https://github.com/tektoncd/catalog/pull/695

### CODE REVIEW

**Comment by alien-ike** [comment]
@bartoszmajsak: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
e2e-tests-openshift | 26fb248cfbe37d1913154ff2e243d941d0a84dab | [link](http://status-prow.apps.workspace.maistra.test/view/gs/ike-prow-logs/pr-logs/pull/maistra_istio-workspace/817/e2e-tests-openshift/1384022798539689984) | `/test openshift`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Review by aslakknutsen — APPROVED** [review]

**Pull request merged**
