### PR TITLE
feat: enables defining strategy templates in custom folder

### LINKED ISSUE #203: Externalize clone templates
Move hardcoded internal templates out into some external form, e.g. ConfigMap

* allow a sort of wildcard import of templates so new ways of cloning can be provided without operator compile

### PR DESCRIPTION
**Pull request by bartoszmajsak**
#### Short description of what this resolves:

Before this change strategy templates used to patch k8s objects were defined in the code. This allows to define them in an arbitrary folder which should be then exposed as environment variable `TEMPLATE_PATH`. This folder should have `.tpl` and `.var` files named after the strategy. Former defined operations whereas the latter have a list of variables that can be set to empty and serves mainly as documentation for what can be passed into the template or contain a default value.

#### Changes proposed in this pull request:

- loading templates from filesystem or assets linked by go-bindata
- handling external template folder by using `TEMPLATE_PATH`
- tests
- minor code improvements as a result of this impl changes

Fixes #203

### CODE REVIEW

**Review by aslakknutsen — APPROVED** [review]

**Comment by alien-ike** [comment]
@bartoszmajsak: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
e2e-tests-openshift | a16a6687da7e063bdb72ab89cf8b82a85e541578 | [link](http://status-prow.apps.workspace.maistra.test/view/gs/ike-prow-logs/pr-logs/pull/maistra_istio-workspace/602/e2e-tests-openshift/1348682243224113152) | `/test openshift`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by alien-ike** [comment]
@bartoszmajsak: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
e2e-tests-openshift | 8159c3888228e0cab17cbe73b8711f0c3770f77e | [link](http://status-prow.apps.workspace.maistra.test/view/gs/ike-prow-logs/pr-logs/pull/maistra_istio-workspace/602/e2e-tests-openshift/1348931258402476032) | `/test openshift`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
