### PR TITLE
release: highlights of v0.0.6

### PR DESCRIPTION
**Pull request by bartoszmajsak**

### CODE REVIEW

**Comment by alien-ike** [comment]
#### ⚠ Failed generating changelog

#### Found unlabeled PRs

* https://github.com/maistra/istio-workspace/pull/659

**Comment by bartoszmajsak** [comment]
wrong target repo/branch ;)

**Comment by bartoszmajsak** [comment]
Observation: unable to push to fork branch

Potential reasons:
- bug in the code
- wrong token (not a collaborator on the source repo)

**Comment by bartoszmajsak** [comment]
Observation: takes release PR as unlabeled, see https://github.com/maistra/istio-workspace/pull/674#issuecomment-775196639

**Pull request closed without merging**
