### PR TITLE
feat(operator): enhances CLI output for CRD with custom columns

### LINKED ISSUE #782: Add custom resource view for cli
##### What can be improved

Provide a custom resource view for the kubectl/oc cli's to better expose the state of the Session

##### Why

Easier view of the Session state.

https://medium.com/@xcoulon/customizing-the-server-side-printing-of-your-kubernetes-custom-resources-1c84b7631686

### PR DESCRIPTION
**Pull request by bartoszmajsak**
#### Short description of what this resolves:

Provides additional columns in CLI description for Session CRD

Before:

```
❯ oc get sessions
NAME           AGE
bartek-lmwwp   54s
```

After:

```
❯ oc get sessions
NAME           REF NAMES     STRATEGIES       ROUTE TYPE   ROUTE NAME       ROUTE VALUE   AGE
bartek-lmwwp   ratings-v1    telepresence     header       ike-session-id   feature-y     54s
```

There seem to be certain limitations in what we can output (very simple JSONPath expressions are supported). See comments in the related issue. 

#### Changes proposed in this pull request:

- custom columns definitions through `// +kubebuilder:printcolumn` annotations

Fixes #782

### CODE REVIEW

**Review by aslakknutsen — APPROVED** [review]

**Comment by aslakknutsen** [comment]
@bartoszmajsak Have you tested this with multiple refs in a single session?

**Comment by bartoszmajsak** [comment]
> @bartoszmajsak Have you tested this with multiple refs in a single session?

Nope, but it seems to be handles. Originally it was always first element, but it seems it's been fixed (found some unit tests in client-go)

**Pull request merged**
