### PR TITLE
release: highlights of v0.0.6

### PR DESCRIPTION
**Pull request by aslakknutsen**
/skip-e2e

### CODE REVIEW

**Review by bartoszmajsak — APPROVED** [review]

**Comment by alien-ike** [comment]
### ℹ️ Available commands

 * `/changelog vX.Y.Z` will append changelog based on the closed PRs since last release to provided release notes.

 * `/release vX.Y.Z` will add release-related commits to this PR on your behalf. 

 * `/shipit` will rebase everything on master branch and trigger actual release process

**Comment by alien-ike** [comment]
🎇 🎉 🎆 New version has been shipped! 🚀🚀🚀

**Pull request merged**
