### PR TITLE
build(deps): bump version of istio.io/api and istio.io/client-go

### PR DESCRIPTION
**Pull request by Humpheh**
#### Short description of what this resolves:

Observed errors on the operator trying to parse istio `VirtualService` resource. We make use of `corsPolicy.allowedOrigins` which was not implemented in the api version used here.

#### Changes proposed in this pull request:

- Update go istio client libraries to latest.

### CODE REVIEW

**Comment by alien-ike** [comment]
Hi @Humpheh. Thanks for your PR.

I'm waiting for a [maistra](https://github.com/orgs/maistra/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/maistra/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=maistra%2Fistio-workspace).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by bartoszmajsak** [comment]
Many thanks for your contribution @Humpheh! We are cutting releases frequently so this change should be out very soon.

If you have any feedback don't hesitate to share in the "Discussions" section!

**Review by aslakknutsen — APPROVED** [review]

**Comment by aslakknutsen** [comment]
The library version we're using seems to contain a mapping bug:

```
AllowOrigin []string `protobuf:"bytes,1,rep,name=allow_origin,json=allowOrigin,proto3" json:"allow_origin,omitempty"`
```

Missing the `s`:)

Nice catch.

**Pull request merged**
