### PR TITLE
chore(make): removes obsolete targets

### PR DESCRIPTION
**Pull request by bartoszmajsak**

### CODE REVIEW

**Comment by alien-ike** [comment]
@bartoszmajsak: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
test-e2e | 71a64ad90b0560088b109b59457722586bd9bf6e | [link]() | `/test test-e2e`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by alien-ike** [comment]
@bartoszmajsak: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
test-e2e | 71a64ad90b0560088b109b59457722586bd9bf6e | [link]() | `/test test-e2e`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by alien-ike** [comment]
@bartoszmajsak: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
test-e2e | 71a64ad90b0560088b109b59457722586bd9bf6e | [link]() | `/test test-e2e`
e2e-test-openshift | 71a64ad90b0560088b109b59457722586bd9bf6e | [link]() | `/test openshift`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by alien-ike** [comment]
@bartoszmajsak: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
test-e2e | 71a64ad90b0560088b109b59457722586bd9bf6e | [link]() | `/test test-e2e`
e2e-test-openshift | 71a64ad90b0560088b109b59457722586bd9bf6e | [link]() | `/test openshift`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Review by aslakknutsen — APPROVED** [review]

**Comment by alien-ike** [comment]
@bartoszmajsak: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
test-e2e | 71a64ad90b0560088b109b59457722586bd9bf6e | [link]() | `/test test-e2e`
e2e-test-openshift | 49363c283c00c67c3009de0ca4a5b9bfa7728ba2 | [link]() | `/test openshift`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by alien-ike** [comment]
@bartoszmajsak: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
test-e2e | 71a64ad90b0560088b109b59457722586bd9bf6e | [link]() | `/test test-e2e`
e2e-test-openshift | 49363c283c00c67c3009de0ca4a5b9bfa7728ba2 | [link]() | `/test openshift`
e2e-tests-openshift | 87c9035db4c62b7b83b8c5db221b945d08bd3cc6 | [link](http://status-prow.apps.workspace.maistra.test/view/gs/ike-prow-logs/pr-logs/pull/maistra_istio-workspace/581/e2e-tests-openshift/1347175314161143808) | `/test openshift`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by alien-ike** [comment]
@bartoszmajsak: The following tests **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
test-e2e | 71a64ad90b0560088b109b59457722586bd9bf6e | [link]() | `/test test-e2e`
e2e-test-openshift | 49363c283c00c67c3009de0ca4a5b9bfa7728ba2 | [link]() | `/test openshift`
e2e-tests-openshift | 92b32b69fc1635b3398db34aec9c894d18e5d784 | [link](http://status-prow.apps.workspace.maistra.test/view/gs/ike-prow-logs/pr-logs/pull/maistra_istio-workspace/581/e2e-tests-openshift/1348931258398281728) | `/test openshift`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
