### PR TITLE
feat(operator): reworks Controller internals to be stateless

### LINKED ISSUE #70: Handle session.status.state
* Accumulate the state based on the Ref state
* Document the possible options

### PR DESCRIPTION
**Pull request by aslakknutsen**
#### Short description of what this resolves:

* single session status.state message
* fully moved to use Conditions
* real-time updates of Conditions
* single location for conversion between external and internal API
* don't rely on Status for storage

#### Changes proposed in this pull request:

- reworked Session model
- rewrote logic for lookup and manipulation of resources
- reworked Controller internals:
   - **Locators**
     Responsible for finding the resources and the appropriate Actions(create, modify, revert, delete) required to satisfy this Ref request.
   - **Modificators**
     Responsible for performing the provided action
   - The Controller Sync can now abort between discovering what needs to be done and doing it, providing the option for overall validation of state and additional reporting.
- fixed Tekton tasks

Fixes #70

### CODE REVIEW

**Comment by alien-ike** [comment]
@aslakknutsen: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
e2e-tests-openshift | a09037d680541bd7f090f7ab3684bce3ff637bae | [link](http://status-prow.apps.workspace.maistra.test/view/gs/ike-prow-logs/pr-logs/pull/maistra_istio-workspace/858/e2e-tests-openshift/1415684523659628544) | `/test openshift`

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Review by bartoszmajsak — APPROVED** [review]
Vida-Starz-season-2-starz-vida-JUqpBP834YjnG88DkV

**Pull request merged**
